{{- if .Values.nordicJourneyPlanner.enabled }}
apiVersion: v1
data:
  build-config.json: |+
   {
      "graph": "${GRAPH_URI}"
   }
kind: ConfigMap
metadata:
  name: otp2nordic-build-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.nordic.labels" . | indent 4 }}
{{- end }}
