{{- if .Values.nordicJourneyPlanner.enabled }}
apiVersion: v1
data:
  # Same URI as the "graph" output of the nordic graph builder (configmap-nordic-graph-builder.yaml).
  build-config.json: |+
   {
      "graph": "{{ .Values.environmentValues.mardukGcpBaseName }}netex-otp2nordic/${otp.serialization.version.id}/graph-${otp.serialization.version.id}.obj"
   }
kind: ConfigMap
metadata:
  name: otp2nordic-build-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.nordic.labels" . | indent 4 }}
  annotations:
    {{- include "common.nordic.annotations" . | indent 4 }}
{{- end }}
