{{- if .Values.cronjobRedeployGraphBuilder.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "graph.builder.labels" . | indent 4 }}
  name: graph-builder-otp2
  namespace: {{ .Release.Namespace }}
data:
  otp-config.json: |+
      {
        "configVersion" : "{{ .Values.build.number }}",
        "otpFeatures" : {
            "ConsiderPatternsForDirectTransfers" : true,
            "Emission" : {{ .Values.features.emission }},
            "GoogleCloudStorage" : true,
            "FlexRouting": true
        }
      }
  build-config.json: |+
      {
        "configVersion" : "{{ .Values.build.number }}",
        "dataImportReport": true,
        "subwayAccessTime": 0,
        "embedRouterConfig": true,
        "areaVisibility": true,
        "platformEntriesLinking": true,
        "staticParkAndRide": true,
        "staticBikeParkAndRide": true,
        "maxDataImportIssuesPerFile": 1000,
        "maxTransferDuration": "30m",
        "distanceBetweenElevationSamples": 25,
        "multiThreadElevationCalculations": true,
        "boardingLocationTags": [],
        // Exclude CAR transfers
        //"transferParametersForMode": {
        //  "CAR": {
        //    "disableDefaultTransfers": true,
        //    "carsAllowedStopMaxTransferDuration": "3h"
        //  }
        //},
        "transferRequests" : [
          {
            "modes" : "WALK"
          },
          {
            "modes" : "WALK",
            "wheelchairAccessibility" : {
              "enabled" : true
            }
          // Exclude BIKE and CAR transfers
          //},
          //{
          //  "modes" : "BICYCLE"
          //},
          //{
          //  "modes" : "CAR"
          }
        ],
        "osmDefaults": {
          "osmTagMapping": "norway",
          "timeZone": "Europe/Oslo"
        },
        "osmCacheDataInMem": "true",
        "osm" : [
          {"source": "gs://{{ .Values.cronjobRedeployGraphBuilder.mardukBucket }}/osm/norway-latest.osm.pbf"},
          {"source": "gs://{{ .Values.cronjobRedeployGraphBuilder.mardukBucket }}/osm/static/osm_static_sweden_extract.pbf"},
          {"source": "gs://{{ .Values.cronjobRedeployGraphBuilder.mardukBucket }}/osm/static/osm_static_sweden_storlien_extract.pbf"}
        ],
        "dem" : [
          {"source": "gs://{{ .Values.cronjobRedeployGraphBuilder.mardukInternalBucket }}/kartverket/heightData/norge_dem_50m_33.tif"}
        ],
        "transitFeeds": [
          {
            "type": "netex",
            "source": "gs://{{ .Values.cronjobRedeployGraphBuilder.mardukBucket }}/outbound/netex/rb_norway-aggregated-netex.zip",
            "sharedFilePattern": "_stops.xml",
            "sharedGroupFilePattern": "_(\\w{3})(_flexible)?_shared_data.xml",
            "groupFilePattern": "(\\w{3})_.*\\.xml",
            "feedId": "RB",
            "ignoreFareFrame": {{ .Values.cronjobRedeployGraphBuilder.ignoreFareFrame }}
          }
        ],
        "emission": {
          "feeds": [
            {
              "feedId": "RB",
              "source": "gs://emissions-to-otp/emissions-to-otp.csv"
            }
          ]
        },
        "streetGraph": "gs://{{ .Values.cronjobRedeployGraphBuilder.mardukInternalBucket }}/${OTP_GCS_BASE_GRAPH_PATH}/streetGraph-otp2-${otp.serialization.version.id}.obj",
        "graph": "gs://{{ .Values.cronjobRedeployGraphBuilder.mardukInternalBucket }}/${OTP_GCS_WORK_DIR}/Graph-otp2-${otp.serialization.version.id}.obj",
        "buildReportDir": "gs://{{ .Values.cronjobRedeployGraphBuilder.mardukInternalBucket }}/${OTP_GCS_WORK_DIR}/report"
      }
{{end}}
