{{- if .Values.journeyPlanner.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
    traffic-type: api
  annotations:
    kubernetes.io/ingress.class: traefik
  name: journey-planner-v3
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: journey-planner-v3{{ .Values.ingress.otpApi.domainName }}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "app.name" . }}
              port:
                number: {{ .Values.service.externalPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
    traffic-type: public
  annotations:
    kubernetes.io/ingress.class: traefik
  name: otp2debug
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: otp2debug{{ .Values.ingress.otpDebug.domainName }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "app.name" . }}
                port:
                  number:  {{ .Values.service.externalPort }}
{{- end }}
