{{- if .Values.journeyPlanner.enabled }}
apiVersion: v1
data:
  otp-config.json: |+
   {
      "otpFeatures": {
        "ActuatorAPI": true,
        "FlexRouting": {{ .Values.configuration.flexRouting }},
        "FloatingBike": {{ .Values.configuration.floatingBike }},
        "IncludeEmptyRailStopsInTransfers" : true,
        "LegacyRestApi" : true,
        "MultiCriteriaGroupMaxFilter" : true,
        "OptimizeTransfers": {{ .Values.configuration.optimizeTransfers }},
        "ParallelRouting": {{ .Values.configuration.parallelRouting }},
        "ReportApi": true,
        "RestAPIPassInDefaultConfigAsJson": {{ .Values.configuration.restApiConfigJsonParam }},
        "Sorlandsbanen" : {{ .Values.configuration.sorlandsbanen }},
        "TransferConstraints": {{ .Values.configuration.transferConstraints }},
        "CarPooling": true
      }
   }
kind: ConfigMap
metadata:
  name: otp2-feature-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
{{- end }}
