{{- if .Values.journeyPlanner.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: {{ template "app.name" . }}
      port: {{ .Values.service.externalPort }}
      protocol: TCP
      {{- if .Values.proxy.exposed }}
      targetPort: {{ .Values.proxy.port }}
      {{- else }}
      targetPort: {{ .Values.service.internalPort }}
      {{- end }}
  selector:
    app: {{ template "app.name" . }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}
