{{- if .Values.cronjobRedeployGraphBuilder.releaseCandidateGraphBuilderEnabled}}
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "graph.builder.labels" . | indent 4 }}
  name: graph-builder-otp2-candidate
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      # delete completed or failed jobs after 3 days (to give some time for error analysis)
      # jobs should normally be deleted automatically by marduk after graph building completion
      ttlSecondsAfterFinished: 259200
      template:
        metadata:
          annotations:
            prometheus.io/path: /metrics
            prometheus.io/port: "9779"
            prometheus.io/scrape: "true"
          labels:
            {{- include "graph.builder.labels" . | indent 12 }}
        spec:
          serviceAccountName: application
          containers:
          - command:
              - "java"
            args:
              - "-server"
              - "-Xms{{ .Values.cronjobRedeployGraphBuilder.resources.xms }}"
              - "-Xmx{{ .Values.cronjobRedeployGraphBuilder.resources.xmx }}"
              - "-XX:MaxGCPauseMillis=5000"
              - "-XX:+UseTransparentHugePages"
              - "--add-opens=java.base/java.lang=ALL-UNNAMED"
              - "--add-opens=java.base/java.nio=ALL-UNNAMED"
              - "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"
              - "-javaagent:/opt/agent-bond/agent-bond.jar=jolokia{{`{{host=0.0.0.0}}`}},jmx_exporter{{`{{9779:/opt/agent-bond/jmx_exporter_config.yml}}`}}"
              - "-Dfile.encoding=UTF-8"
              - "-Dlogback.configurationFile=/etc/otp2/logback.xml"
              - "-Dentur.otp.service.name=otp2-gb"
              - "-jar"
              - "otp-shaded.jar"
              - "$(OTP_GRAPH_MODE)"
              - "/etc/application-config"
              - "--save"
            env:
            - name: TZ
              value: Europe/Oslo
            image: {{ .Values.image.identifier }}
            imagePullPolicy: {{ .Values.cronjobRedeployGraphBuilder.imagePullPolicy }}
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /metrics
                port: 9779
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 30
            name: graph-builder-otp2-candidate
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /metrics
                port: 9779
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 20
            resources:
              limits:
                cpu: {{ .Values.cronjobRedeployGraphBuilder.resources.cpuLimit }}
                memory: {{ .Values.cronjobRedeployGraphBuilder.resources.memLimit }}
              requests:
                cpu: {{ .Values.cronjobRedeployGraphBuilder.resources.cpuRequest }}
                memory: {{ .Values.cronjobRedeployGraphBuilder.resources.memRequest }}
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              capabilities:
                drop: [ "ALL" ]
              seccompProfile:
                type: RuntimeDefault
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/application-config
              name: application-config
              readOnly: true
            - mountPath: /etc/otp2/logback.xml
              name: logback-config-volume
              subPath: logback.xml  
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: graph-builder-otp2-candidate
            name: application-config
          - configMap:
              defaultMode: 420
              name: otp2-logback-config-graph-builder-candidate
            name: logback-config-volume  
      backoffLimit: 0
  # the cron job should never run as it is used only as a template for creating new jobs.
  schedule: 0 0 1 1 0
  successfulJobsHistoryLimit: 1
  # the cron job should never run as it is used only as a template for creating new jobs.
  suspend: true
{{end}}