{{- if .Values.journeyPlanner.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  progressDeadlineSeconds: 1200
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /otp/actuators/prometheus
        prometheus.io/port: {{ .Values.service.internalPort }}
        prometheus.io/scrape: "true"
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - otp
                        - otp2
                topologyKey: kubernetes.io/hostname
              weight: 100
      serviceAccountName: application
      containers:
      {{- if .Values.proxy.enabled }}
      - image: {{ .Values.proxy.image.repo }}
        env:
        - name: API_SCHEME
          value: http
        - name: API_HOST
          value: 127.0.0.1
        - name: API_PORT
          value: "{{ .Values.service.internalPort }}"
        - name: GOOGLE_PUBSUB_PROJECT_ID
          value: {{ .Values.proxy.googlePubsubProjectId }}
        - name: GOOGLE_PUBSUB_REQUEST_TOPIC
          value: {{ .Values.proxy.googlePubsubRequestTopic }}
        - name: GOOGLE_PUBSUB_RESPONSE_TOPIC
          value: {{ .Values.proxy.googlePubsubResponseTopic }}
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 15
        name: {{ .Chart.Name }}-proxy
        ports:
          - containerPort: {{ .Values.proxy.port }}
            protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.proxy.resources.cpuRequest }}
            memory: {{ .Values.proxy.resources.memRequest }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: [ "ALL" ]
          seccompProfile:
            type: RuntimeDefault
      {{- end }}
      - image: {{ .Values.image.identifier }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command:
        - /docker-entrypoint.sh
        - java
        - -Dfile.encoding=UTF-8
        - -Dtransmodel.graphql.api.agency.id=RB
        - -Duser.language=no
        - -Xms{{ .Values.resources.xms }}
        - -Xmx{{ .Values.resources.xmx }}
        - -XX:+UseTransparentHugePages
        - -XX:+AlwaysPreTouch
        - -XX:ActiveProcessorCount={{ .Values.resources.cpuRequest }}
        - --add-opens=java.base/java.lang=ALL-UNNAMED
        - --add-opens=java.base/java.nio=ALL-UNNAMED
        - --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
        - -server
        - -Dcom.sun.management.jmxremote
        - -Dcom.sun.management.jmxremote.port=9010
        - -Dcom.sun.management.jmxremote.local.only=false
        - -Dcom.sun.management.jmxremote.authenticate=false
        - -Dcom.sun.management.jmxremote.ssl=false
        - -Dlogback.configurationFile=/etc/otp2/logback.xml
        - -Dentur.otp.service.name=otp2
        - -jar
        - otp-shaded.jar
        - --load
        - /code/otpdata/norway
        - --maxThreads
        - {{ .Values.maxConcurrentRoutingRequests }}
        - --serve
        env:
        - name: TZ
          value: Europe/Oslo
        - name: MARDUK_GCP_BASE
          value: {{ .Values.environmentValues.mardukGcpBaseName }}
        - name: GRAPH_POINTER_FILE
          value: current-otp2
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 15
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /otp/actuators/health
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 2
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /otp/actuators/health
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        startupProbe:
          failureThreshold: 42
          httpGet:
            path: /otp/actuators/health
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: {{ .Values.resources.cpuLimit }}
            memory: {{ .Values.resources.memLimit }}
          requests:
            cpu: {{ .Values.resources.cpuRequest }}
            memory: {{ .Values.resources.memRequest }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: [ "ALL" ]
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: router-config-volume
          mountPath: /code/otpdata/norway/router-config.json
          subPath: router-config.json
        - name: feature-config-volume
          mountPath: /code/otpdata/norway/otp-config.json
          subPath: otp-config.json
        - mountPath: /etc/otp2/logback.xml
          name: logback-config-volume
          subPath: logback.xml  
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 61
      volumes:
      - configMap:
          defaultMode: 420
          name: otp2-router-config
        name: router-config-volume
      - configMap:
          defaultMode: 420
          name: otp2-feature-config
        name: feature-config-volume
      - configMap:
          defaultMode: 420
          name: otp2-logback-config
        name: logback-config-volume  
{{- end }}
