{{- if and (.Values.journeyPlanner.enabled) (.Values.horizontalPodAutoscaler.enabled) (gt .Values.replicas 1.0) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  maxReplicas:  {{ .Values.horizontalPodAutoscaler.maxReplicas | default "2" }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.minReplicas | default "1" }} 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "app.name" . }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalPodAutoscaler.targetCPUUtilizationPercentage | default "80" }}
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 180
      stabilizationWindowSeconds : 300
{{- end }}