{{- if .Values.nordicJourneyPlanner.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "common.nordic.labels" . | indent 4 }}
    traffic-type: api
  annotations:
    kubernetes.io/ingress.class: traefik
  name: nordic-journey-planner-v3
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: nordic-journey-planner-v3{{ .Values.ingress.otpApi.domainName }}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: otp2nordic
              port:
                number: {{ .Values.service.externalPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "common.nordic.labels" . | indent 4 }}
    traffic-type: public
  annotations:
    kubernetes.io/ingress.class: traefik
  name: otp2debug-nordic
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: otp2debug-nordic{{ .Values.ingress.otpDebug.domainName }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: otp2nordic
                port:
                  number: {{ .Values.service.externalPort }}
{{- end }}
