journeyPlanner:
  enabled: false
cronjobRedeployGraphBuilder:
    releaseCandidateGraphBuilderEnabled: true
    mardukBucket: marduk-production
    mardukInternalBucket: ror-marduk-internal-production
    ignoreFareFrame: false