env: jp-dev

replicas: 2

horizontalPodAutoscaler:
  enabled: true
  maxReplicas: 10
  minReplicas: 2
  targetCPUUtilizationPercentage: 70

rollingUpdate:
  maxSurge: 0
  maxUnavailable: 1

resources:
  cpuLimit: "8"
  memLimit: 14000Mi
  cpuRequest: "2"
  memRequest: 13000Mi
  xmx: 13g
  xms: 7g

configMap:
  logbackConfig: env/logback.xml

environmentValues:
  mardukGcpBaseName: "gs://otp-graphs-dev/"


configmapMounts:
  - name: config-volume
    mountPath: /code/otpdata/norway/router-config.json
    subPath: router-config.json
    configMap: otp-router-config
    readOnly: true

image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always

build:
  number: <+artifacts.primary.tag>

service:
    externalPort: 8080
    internalPort: 8080

journeyPlanner:
  enabled: true
nordicJourneyPlanner:
  enabled: false
proxy:
  enabled: false
  exposed: false
  port: 8000
  resources:
    cpuRequest: 100m
    memRequest: 100Mi
  image:
    repo: eu.gcr.io/entur-system-1287/otp2-proxy:0.0.27

cronjobRedeployGraphBuilder:
  releaseCandidateGraphBuilderEnabled: false
  enabled: false
  imagePullPolicy: Always
  resources:
    cpuLimit: 5000m
    memLimit: 26000Mi
    cpuRequest: 5000m
    memRequest: 24000Mi
    xmx: 20g
    xms: 512m

cronjobRedeployOtp2:
  enabled: true
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  resources:
    cpuLimit: 900m
    memLimit: 2550Mi
    cpuRequest: 100m
    memRequest: 1000m
  image:
    repo: eu.gcr.io/entur-system-1287/deployment-rollout-restart:0.1.9

secrets:
  otp2-secrets:
   - SLACK_URL
