{{- if .Values.nordicJourneyPlanner.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "nordic.graph.builder.labels" . | indent 4 }}
  name: graph-builder-otp2nordic
  namespace: {{ .Release.Namespace }}
data:
  otp-config.json: |+
    {
      "configVersion": "{{ .Values.build.number }}",
      "otpFeatures": {
        "GoogleCloudStorage": true,
        "FlexRouting": true
      }
    }
  build-config.json: |+
    {
      "configVersion": "{{ .Values.build.number }}",
      "dataImportReport": true,
      "subwayAccessTime": 0,
      "embedRouterConfig": true,
      "areaVisibility": true,
      "platformEntriesLinking": true,
      "staticParkAndRide": true,
      "staticBikeParkAndRide": true,
      "maxDataImportIssuesPerFile": 1000,
      "maxTransferDuration": "30m",
      "distanceBetweenElevationSamples": 25,
      "multiThreadElevationCalculations": true,
      "streetGraph": "gs://ror-marduk-internal-dev/otp2nordic/street/${otp.serialization.version.id}.obj",
      "graph": "gs://ror-otp-graphs-gcp2-dev/netex-otp2nordic/${otp.serialization.version.id}/graph-${otp.serialization.version.id}.obj",
      "buildReportDir": "gs://ror-marduk-internal-dev/otp2nordic/report",
      "transitModelTimeZone": "Europe/Oslo",
      "osmCacheDataInMem": "true",
      "gtfsDefaults" : {
          "discardMinTransferTimes": true,
          "maxInterlineDistance" : 200
      },
      "osm": [
        {
          "source": "https://download.geofabrik.de/europe/norway-latest.osm.pbf",
          "osmTagMapping": "norway",
          "timeZone": "Europe/Oslo"
        },
        {
          "source": "https://download.geofabrik.de/europe/sweden-latest.osm.pbf",
          "osmTagMapping": "default",
          "timeZone": "Europe/Stockholm"
        },
        {
          "source": "https://download.geofabrik.de/europe/finland-latest.osm.pbf",
          "osmTagMapping": "finland",
          "timeZone": "Europe/Helsinki"
        },
        {
          "source": "https://download.geofabrik.de/europe/denmark-latest.osm.pbf",
          "osmTagMapping": "default",
          "timeZone": "Europe/Copenhagen"
        }
      ],
      "transitFeeds": [
        {
          "type": "netex",
          "feedId": "NO",
          "source": "gs://marduk-production/outbound/netex/rb_norway-aggregated-netex.zip",
          "sharedFilePattern": "_stops.xml",
          "sharedGroupFilePattern": "_(\\w{3})(_flexible)?_shared_data.xml",
          "groupFilePattern": "(\\w{3})_.*\\.xml"
        },
        {
          "type": "gtfs",
          "feedId": "FI",
          "source": "https://mobility.mobility-database.fintraffic.fi/static/finland_gtfs.zip"
        },
        {
          "type": "netex",
          "feedId": "SE",
          "source": "https://opendata.samtrafiken.se/netex-sweden/sweden.zip?key=${SAMTRAFIKEN_API_KEY}",
          "sharedFilePattern": "_stops.xml|_shared_data.xml",
          "groupFilePattern": "line_([0-9]*)_.*\\.xml"
        },
        {
          "type": "gtfs",
          "feedId": "DK",
          "source": "https://www.rejseplanen.info/labs/GTFS.zip"
        },
        {
          "type": "gtfs",
          "feedId": "VK",
          "source": "https://fgwgtfsprod.blob.core.windows.net/gtfsout/latest_VIKINGLINE.zip"
        },
        {
          "type": "gtfs",
          "feedId": "FL",
          "source": "https://finap.fi/export/gtfs/1660"
        }
      ]
    }
{{end}}
