{{- if .Values.nordicJourneyPlanner.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common.nordic.labels" . | indent 4 }}
  name: otp2nordic
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: otp2nordic
      port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: otp2nordic
  sessionAffinity: None
  type: ClusterIP
{{- end }}
