name: Entur - Release OTP Maven project
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - debug
  schedule:
    - cron: '33 0 * * *'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout entur/OpenTripPlanner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: actions/setup-java@v4
        with:
          java-version: 21.0.5+11
          distribution: liberica
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-
            ${{ runner.os }}-
      - name: Release OTP
        env:
          CUSTOM_RELEASE_GIT_HUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_RELEASE_LOG_LEVEL: ${{ inputs.logLevel }}
        run: |
          echo "Start otp release script"
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote rename origin entur
          git remote add otp https://github.com/opentripplanner/OpenTripPlanner.git
          git fetch --no-tags otp
          git remote -v
          echo "Run script/custom-release.py otp/dev-2.x"
          script/custom-release.py otp/dev-2.x
          echo "GHA_DOCKER_PUSH_IMAGE_TAG=`git describe --tags --abbrev=0`" >> $GITHUB_ENV
      - name: Trigger downstream CI
        run: |
          repo_owner="entur"
          repo_name="OpenTripPlanner"
          event_type="trigger-downstream-ci"
          service="otp"   
          echo "Triggering downstream CI for $service with version $GHA_DOCKER_PUSH_IMAGE_TAG"
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITFLOW_PAT }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
          -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$GHA_DOCKER_PUSH_IMAGE_TAG\", \"unit\": false, \"integration\": true}}"
          
          