name: Integration test

on:
  pull_request:
    types:
      - labeled
env:
  # Since version 3.9.0 of Maven it will automatically understand this environment variable.
  # However, as of 2024-11 the latest versions of Ubuntu and Debian were on 3.8.8 so it will take some
  # time until we can remove the $MAVEN_ARGS below.
  MAVEN_ARGS: "--no-transfer-progress -Dstyle.color=always"

jobs:
  run:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'Integration test' )
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven


      - name: Run integration tests
        run: mvn test-compile failsafe:integration-test -PprettierSkip