name: Integration test

on:
  pull_request:
    types:
      - labeled
      - synchronize
env:
  MAVEN_ARGS: "--no-transfer-progress -Dstyle.color=always"

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'opentripplanner' && contains( github.event.pull_request.labels.*.name, 'Integration Test' )
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven


      - name: Run integration tests
        # the documentation of the surefire plugin says that the excludedGroups and includedGroups
        # should work directly from the command line, but i cannot get it to work.
        # for that reason i need the detour via the maven properties.
        # from my understanding setting excludedGroups should not be necessary, but it is. ¯\_(ツ)_/¯
        # if you are an expert of the surefire plugin, feel free to correct this.
        run: mvn test -P integration-test

