name: Manual OTP Release
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prd'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Release OTP
        env:
          GIT_HUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Start otp release script"
          git remote add entur  https://github.com/entur/OpenTripPlanner.git
          git remote add otp https://github.com/opentripplanner/OpenTripPlanner.git
          git remote -v
          chmod +x script/custom-release.py
          script/custom-release.py --dryRun otp/dev-2.x
          
          